
package firstaidapp;


public class LessonsList extends javax.swing.JFrame {

    /**
     * Creates new form LessonsList
     */
    public LessonsList() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(255, 255, 255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        FirstAidLessonButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        CPRButton = new javax.swing.JButton();
        UnresponsiveBreathingButton = new javax.swing.JButton();
        HeavyBleedingButton = new javax.swing.JButton();
        BurnsButton = new javax.swing.JButton();
        ChokingButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        FirstAidLessonButton3.setBackground(new java.awt.Color(249, 6, 6));
        FirstAidLessonButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageFile/Heavy-Bleeding LessonList.png"))); // NOI18N
        FirstAidLessonButton3.setMaximumSize(new java.awt.Dimension(159, 169));
        FirstAidLessonButton3.setMinimumSize(new java.awt.Dimension(159, 169));
        FirstAidLessonButton3.setPreferredSize(new java.awt.Dimension(290, 90));
        FirstAidLessonButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstAidLessonButton3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(360, 640));
        setMinimumSize(new java.awt.Dimension(360, 640));
        setName("LessonsList"); // NOI18N
        setUndecorated(true);
        getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageFile/back.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 13, 30, 60);

        CPRButton.setBackground(new java.awt.Color(249, 6, 6));
        CPRButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageFile/CPR LessonList.png"))); // NOI18N
        CPRButton.setMaximumSize(new java.awt.Dimension(159, 169));
        CPRButton.setMinimumSize(new java.awt.Dimension(159, 169));
        CPRButton.setPreferredSize(new java.awt.Dimension(290, 90));
        CPRButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPRButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CPRButton);
        CPRButton.setBounds(34, 101, 290, 90);

        UnresponsiveBreathingButton.setBackground(new java.awt.Color(249, 6, 6));
        UnresponsiveBreathingButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageFile/Unresponsive-Breathing LessonList.png"))); // NOI18N
        UnresponsiveBreathingButton.setMaximumSize(new java.awt.Dimension(159, 169));
        UnresponsiveBreathingButton.setMinimumSize(new java.awt.Dimension(159, 169));
        UnresponsiveBreathingButton.setPreferredSize(new java.awt.Dimension(290, 90));
        UnresponsiveBreathingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnresponsiveBreathingButtonActionPerformed(evt);
            }
        });
        getContentPane().add(UnresponsiveBreathingButton);
        UnresponsiveBreathingButton.setBounds(34, 202, 290, 90);

        HeavyBleedingButton.setBackground(new java.awt.Color(249, 6, 6));
        HeavyBleedingButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageFile/Heavy-Bleeding LessonList.png"))); // NOI18N
        HeavyBleedingButton.setMaximumSize(new java.awt.Dimension(159, 169));
        HeavyBleedingButton.setMinimumSize(new java.awt.Dimension(159, 169));
        HeavyBleedingButton.setPreferredSize(new java.awt.Dimension(290, 90));
        HeavyBleedingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HeavyBleedingButtonActionPerformed(evt);
            }
        });
        getContentPane().add(HeavyBleedingButton);
        HeavyBleedingButton.setBounds(34, 303, 290, 90);

        BurnsButton.setBackground(new java.awt.Color(249, 6, 6));
        BurnsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageFile/Burns LessonList.png"))); // NOI18N
        BurnsButton.setMaximumSize(new java.awt.Dimension(159, 169));
        BurnsButton.setMinimumSize(new java.awt.Dimension(159, 169));
        BurnsButton.setPreferredSize(new java.awt.Dimension(290, 90));
        BurnsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BurnsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BurnsButton);
        BurnsButton.setBounds(34, 411, 290, 90);

        ChokingButton.setBackground(new java.awt.Color(249, 6, 6));
        ChokingButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageFile/Choking LessonList.png"))); // NOI18N
        ChokingButton.setMaximumSize(new java.awt.Dimension(159, 169));
        ChokingButton.setMinimumSize(new java.awt.Dimension(159, 169));
        ChokingButton.setPreferredSize(new java.awt.Dimension(290, 90));
        ChokingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChokingButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ChokingButton);
        ChokingButton.setBounds(34, 519, 290, 90);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageFile/lessonScreen.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(-20, 0, 380, 140);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CPRButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPRButtonActionPerformed
        new LessonsList().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CPRButtonActionPerformed

    private void UnresponsiveBreathingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnresponsiveBreathingButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UnresponsiveBreathingButtonActionPerformed

    private void HeavyBleedingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HeavyBleedingButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HeavyBleedingButtonActionPerformed

    private void FirstAidLessonButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstAidLessonButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstAidLessonButton3ActionPerformed

    private void BurnsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BurnsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BurnsButtonActionPerformed

    private void ChokingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChokingButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChokingButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Menu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LessonsList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LessonsList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LessonsList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LessonsList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LessonsList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BurnsButton;
    private javax.swing.JButton CPRButton;
    private javax.swing.JButton ChokingButton;
    private javax.swing.JButton FirstAidLessonButton3;
    private javax.swing.JButton HeavyBleedingButton;
    private javax.swing.JButton UnresponsiveBreathingButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
