package firstaidapp;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Color;
/**
 *
 * @author up839921
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        QuizButton = new javax.swing.JButton();
        FirstAidLessonButton = new javax.swing.JButton();
        PreviewResultsButton = new javax.swing.JButton();
        ScoresButton = new javax.swing.JButton();
        EmergencyButton = new javax.swing.JButton();
        SettingsButton = new javax.swing.JButton();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(360, 640));
        setResizable(false);
        setSize(new java.awt.Dimension(360, 640));

        QuizButton.setBackground(new java.awt.Color(249, 6, 6));
        QuizButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuizButtonActionPerformed(evt);
            }
        });

        FirstAidLessonButton.setBackground(new java.awt.Color(249, 6, 6));
        FirstAidLessonButton.setMaximumSize(new java.awt.Dimension(159, 169));
        FirstAidLessonButton.setMinimumSize(new java.awt.Dimension(159, 169));
        FirstAidLessonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstAidLessonButtonActionPerformed(evt);
            }
        });

        PreviewResultsButton.setBackground(new java.awt.Color(249, 6, 6));
        PreviewResultsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreviewResultsButtonActionPerformed(evt);
            }
        });

        ScoresButton.setBackground(new java.awt.Color(249, 6, 6));
        ScoresButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScoresButtonActionPerformed(evt);
            }
        });

        EmergencyButton.setBackground(new java.awt.Color(249, 6, 6));
        EmergencyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmergencyButtonActionPerformed(evt);
            }
        });

        SettingsButton.setBackground(new java.awt.Color(249, 6, 6));
        SettingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(PreviewResultsButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(EmergencyButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(FirstAidLessonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(QuizButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ScoresButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SettingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FirstAidLessonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QuizButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PreviewResultsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ScoresButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SettingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmergencyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EmergencyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmergencyButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmergencyButtonActionPerformed

    private void PreviewResultsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreviewResultsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PreviewResultsButtonActionPerformed

    private void FirstAidLessonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstAidLessonButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstAidLessonButtonActionPerformed

    private void QuizButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuizButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuizButtonActionPerformed

    private void ScoresButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScoresButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ScoresButtonActionPerformed

    private void SettingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingsButtonActionPerformed
        // TODO add your handling code here:
        new Settings().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_SettingsButtonActionPerformed

    public void defaultColoursMenu(){
        FirstAidLessonButton.setBackground(new Color(249, 6, 6));
        QuizButton.setBackground(new Color(249, 6, 6));
        PreviewResultsButton.setBackground(new Color(249, 6, 6));
        ScoresButton.setBackground(new Color(249, 6, 6));
        EmergencyButton.setBackground(new Color(249, 6, 6));
        SettingsButton.setBackground(new Color(249, 6, 6));  
    }
    
    public void DeuteranopiaColoursMenu(){
        FirstAidLessonButton.setBackground(new Color(238, 43, 150));
        QuizButton.setBackground(new Color(238, 43, 150));
        PreviewResultsButton.setBackground(new Color(238, 43, 150));
        ScoresButton.setBackground(new Color(238, 43, 150));
        EmergencyButton.setBackground(new Color(238, 43, 150));
        SettingsButton.setBackground(new Color(238, 43, 150));  
    }
    
    public void ProtanopiaColoursMenu(){
        FirstAidLessonButton.setBackground(new Color(250, 56, 143));
        QuizButton.setBackground(new Color(250, 56, 143));
        PreviewResultsButton.setBackground(new Color(250, 56, 143));
        ScoresButton.setBackground(new Color(250, 56, 143));
        EmergencyButton.setBackground(new Color(250, 56, 143));
        SettingsButton.setBackground(new Color(250, 56, 143));  
    }
    
    public void TritanopiaColoursMenu(){
        FirstAidLessonButton.setBackground(new Color(255, 0, 0));
        QuizButton.setBackground(new Color(255, 0, 0));
        PreviewResultsButton.setBackground(new Color(255, 0, 0));
        ScoresButton.setBackground(new Color(255, 0, 0));
        EmergencyButton.setBackground(new Color(255, 0, 0));
        SettingsButton.setBackground(new Color(255, 0, 0));
    }
        
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EmergencyButton;
    private javax.swing.JButton FirstAidLessonButton;
    private javax.swing.JButton PreviewResultsButton;
    private javax.swing.JButton QuizButton;
    private javax.swing.JButton ScoresButton;
    private javax.swing.JButton SettingsButton;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables


}
