/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package firstaidapp;

import java.awt.Color;

/**
 *
 * @author up839921
 */
public class Settings extends javax.swing.JFrame {

    /**
     * Creates new form Settings
     */
    public Settings() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DefaultColours = new javax.swing.JRadioButton();
        DeuteranopiaColours = new javax.swing.JRadioButton();
        ProtanopiaColours = new javax.swing.JRadioButton();
        TritanopiaColours = new javax.swing.JRadioButton();
        RedColourTest = new javax.swing.JPanel();
        GreenColourTest = new javax.swing.JPanel();
        BlueColourTest = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(360, 640));
        setResizable(false);
        setSize(new java.awt.Dimension(360, 640));

        DefaultColours.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        DefaultColours.setSelected(true);
        DefaultColours.setText("Default");
        DefaultColours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefaultColoursActionPerformed(evt);
            }
        });

        DeuteranopiaColours.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        DeuteranopiaColours.setText("Deuteranopia");
        DeuteranopiaColours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeuteranopiaColoursActionPerformed(evt);
            }
        });

        ProtanopiaColours.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        ProtanopiaColours.setText("Protanopia");
        ProtanopiaColours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProtanopiaColoursActionPerformed(evt);
            }
        });

        TritanopiaColours.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        TritanopiaColours.setText("Tritanopia");
        TritanopiaColours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TritanopiaColoursActionPerformed(evt);
            }
        });

        RedColourTest.setBackground(new java.awt.Color(249, 6, 6));
        RedColourTest.setBorder(new javax.swing.border.SoftBevelBorder(50));
        RedColourTest.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout RedColourTestLayout = new javax.swing.GroupLayout(RedColourTest);
        RedColourTest.setLayout(RedColourTestLayout);
        RedColourTestLayout.setHorizontalGroup(
            RedColourTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );
        RedColourTestLayout.setVerticalGroup(
            RedColourTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        GreenColourTest.setBackground(new java.awt.Color(0, 128, 0));
        GreenColourTest.setBorder(new javax.swing.border.SoftBevelBorder(50));
        GreenColourTest.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout GreenColourTestLayout = new javax.swing.GroupLayout(GreenColourTest);
        GreenColourTest.setLayout(GreenColourTestLayout);
        GreenColourTestLayout.setHorizontalGroup(
            GreenColourTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );
        GreenColourTestLayout.setVerticalGroup(
            GreenColourTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        BlueColourTest.setBackground(new java.awt.Color(77, 77, 255));
        BlueColourTest.setBorder(new javax.swing.border.SoftBevelBorder(50));
        BlueColourTest.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout BlueColourTestLayout = new javax.swing.GroupLayout(BlueColourTest);
        BlueColourTest.setLayout(BlueColourTestLayout);
        BlueColourTestLayout.setHorizontalGroup(
            BlueColourTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );
        BlueColourTestLayout.setVerticalGroup(
            BlueColourTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(RedColourTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(GreenColourTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(BlueColourTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TritanopiaColours)
                    .addComponent(ProtanopiaColours)
                    .addComponent(DeuteranopiaColours)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DefaultColours)
                        .addGap(64, 64, 64)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(285, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RedColourTest, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GreenColourTest, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BlueColourTest, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(DefaultColours)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DeuteranopiaColours)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProtanopiaColours)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TritanopiaColours)
                .addGap(131, 131, 131))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DefaultColoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefaultColoursActionPerformed
        RedColourTest.setBackground(new Color(249, 6, 6));
        BlueColourTest.setBackground(new Color(0, 128, 0));
        GreenColourTest.setBackground(new Color(77, 77, 255));
    }//GEN-LAST:event_DefaultColoursActionPerformed

    private void DeuteranopiaColoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeuteranopiaColoursActionPerformed
        RedColourTest.setBackground(new Color(238, 43, 150));
        BlueColourTest.setBackground(new Color(0, 155, 33));
        GreenColourTest.setBackground(new Color(0, 64, 224));
    }//GEN-LAST:event_DeuteranopiaColoursActionPerformed

    private void ProtanopiaColoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProtanopiaColoursActionPerformed
        RedColourTest.setBackground(new Color(250, 56, 143));
        BlueColourTest.setBackground(new Color(0, 128, 28));
        GreenColourTest.setBackground(new Color(6, 68, 224));
    }//GEN-LAST:event_ProtanopiaColoursActionPerformed

    private void TritanopiaColoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TritanopiaColoursActionPerformed
        RedColourTest.setBackground(new Color(255, 0, 0));
        BlueColourTest.setBackground(new Color(0, 179, 60));
        GreenColourTest.setBackground(new Color(0, 0, 196));
    }//GEN-LAST:event_TritanopiaColoursActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Settings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BlueColourTest;
    private javax.swing.JRadioButton DefaultColours;
    private javax.swing.JRadioButton DeuteranopiaColours;
    private javax.swing.JPanel GreenColourTest;
    private javax.swing.JRadioButton ProtanopiaColours;
    private javax.swing.JPanel RedColourTest;
    private javax.swing.JRadioButton TritanopiaColours;
    // End of variables declaration//GEN-END:variables
}
