/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package firstaidapp;

import java.awt.*;

/**
 *
 * @author up839921
 */
public class Settings extends javax.swing.JFrame {
    
    /**
     * Creates new form Settings
     */
    public Settings() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ColourblindButtonGroup = new javax.swing.ButtonGroup();
        DefaultColours = new javax.swing.JRadioButton();
        DeuteranopiaColours = new javax.swing.JRadioButton();
        ProtanopiaColours = new javax.swing.JRadioButton();
        TritanopiaColours = new javax.swing.JRadioButton();
        RedColourTest = new javax.swing.JPanel();
        GreenColourTest = new javax.swing.JPanel();
        BlueColourTest = new javax.swing.JPanel();
        Seperator2 = new javax.swing.JPanel();
        ColourblindModeLabel = new javax.swing.JLabel();
        Seperator1 = new javax.swing.JPanel();
        AccessibilityOptionsLabel = new javax.swing.JLabel();
        MagnifyTextCheckBox = new javax.swing.JCheckBox();
        CaptionImagesCheckBox = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(360, 640));
        setResizable(false);
        setSize(new java.awt.Dimension(360, 640));

        ColourblindButtonGroup.add(DefaultColours);
        DefaultColours.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        DefaultColours.setSelected(true);
        DefaultColours.setText("Default");
        DefaultColours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefaultColoursActionPerformed(evt);
            }
        });

        ColourblindButtonGroup.add(DeuteranopiaColours);
        DeuteranopiaColours.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        DeuteranopiaColours.setText("Deuteranopia");
        DeuteranopiaColours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeuteranopiaColoursActionPerformed(evt);
            }
        });

        ColourblindButtonGroup.add(ProtanopiaColours);
        ProtanopiaColours.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        ProtanopiaColours.setText("Protanopia");
        ProtanopiaColours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProtanopiaColoursActionPerformed(evt);
            }
        });

        ColourblindButtonGroup.add(TritanopiaColours);
        TritanopiaColours.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        TritanopiaColours.setText("Tritanopia");
        TritanopiaColours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TritanopiaColoursActionPerformed(evt);
            }
        });

        RedColourTest.setBackground(new java.awt.Color(249, 6, 6));
        RedColourTest.setBorder(new javax.swing.border.SoftBevelBorder(50));
        RedColourTest.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout RedColourTestLayout = new javax.swing.GroupLayout(RedColourTest);
        RedColourTest.setLayout(RedColourTestLayout);
        RedColourTestLayout.setHorizontalGroup(
            RedColourTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );
        RedColourTestLayout.setVerticalGroup(
            RedColourTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        GreenColourTest.setBackground(new java.awt.Color(0, 128, 0));
        GreenColourTest.setBorder(new javax.swing.border.SoftBevelBorder(50));
        GreenColourTest.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout GreenColourTestLayout = new javax.swing.GroupLayout(GreenColourTest);
        GreenColourTest.setLayout(GreenColourTestLayout);
        GreenColourTestLayout.setHorizontalGroup(
            GreenColourTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );
        GreenColourTestLayout.setVerticalGroup(
            GreenColourTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        BlueColourTest.setBackground(new java.awt.Color(77, 77, 255));
        BlueColourTest.setBorder(new javax.swing.border.SoftBevelBorder(50));
        BlueColourTest.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout BlueColourTestLayout = new javax.swing.GroupLayout(BlueColourTest);
        BlueColourTest.setLayout(BlueColourTestLayout);
        BlueColourTestLayout.setHorizontalGroup(
            BlueColourTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );
        BlueColourTestLayout.setVerticalGroup(
            BlueColourTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        Seperator2.setBackground(new java.awt.Color(249, 6, 6));
        Seperator2.setPreferredSize(new java.awt.Dimension(300, 3));

        javax.swing.GroupLayout Seperator2Layout = new javax.swing.GroupLayout(Seperator2);
        Seperator2.setLayout(Seperator2Layout);
        Seperator2Layout.setHorizontalGroup(
            Seperator2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        Seperator2Layout.setVerticalGroup(
            Seperator2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        ColourblindModeLabel.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        ColourblindModeLabel.setText("Colourblind Mode:");

        Seperator1.setBackground(new java.awt.Color(249, 6, 6));
        Seperator1.setPreferredSize(new java.awt.Dimension(300, 3));

        javax.swing.GroupLayout Seperator1Layout = new javax.swing.GroupLayout(Seperator1);
        Seperator1.setLayout(Seperator1Layout);
        Seperator1Layout.setHorizontalGroup(
            Seperator1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        Seperator1Layout.setVerticalGroup(
            Seperator1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        AccessibilityOptionsLabel.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        AccessibilityOptionsLabel.setText("Accessibility options");

        MagnifyTextCheckBox.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        MagnifyTextCheckBox.setText("Magnify Text");
        MagnifyTextCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MagnifyTextCheckBoxActionPerformed(evt);
            }
        });

        CaptionImagesCheckBox.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        CaptionImagesCheckBox.setText("Caption Images");
        CaptionImagesCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaptionImagesCheckBoxActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(RedColourTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(GreenColourTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(BlueColourTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ColourblindModeLabel)
                            .addComponent(TritanopiaColours)
                            .addComponent(ProtanopiaColours)
                            .addComponent(DeuteranopiaColours)
                            .addComponent(DefaultColours)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AccessibilityOptionsLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Seperator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CaptionImagesCheckBox)
                                    .addComponent(MagnifyTextCheckBox)))
                            .addComponent(Seperator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jButton1)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(AccessibilityOptionsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Seperator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MagnifyTextCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CaptionImagesCheckBox)
                .addGap(28, 28, 28)
                .addComponent(Seperator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ColourblindModeLabel)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RedColourTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GreenColourTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BlueColourTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(DefaultColours)
                .addGap(0, 0, 0)
                .addComponent(DeuteranopiaColours)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProtanopiaColours)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TritanopiaColours)
                .addGap(131, 131, 131))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DefaultColoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefaultColoursActionPerformed
        defaultColoursSettings();
        //defaultColoursMenu();
    }//GEN-LAST:event_DefaultColoursActionPerformed

    private void DeuteranopiaColoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeuteranopiaColoursActionPerformed
        DeuteranopiaColoursSettings();
        Utility DeuteranopiaObj = new Utility();
        DeuteranopiaObj.Deuteranopia();
//DeuteranopiaColoursMenu();
    }//GEN-LAST:event_DeuteranopiaColoursActionPerformed

    private void ProtanopiaColoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProtanopiaColoursActionPerformed
        ProtanopiaColoursSettings();
        //ProtanopiaColoursMenu();
    }//GEN-LAST:event_ProtanopiaColoursActionPerformed

    private void TritanopiaColoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TritanopiaColoursActionPerformed
        TritanopiaColoursSettings();
        //firstaidapp.Menu.TritanopiaColoursMenu();
    }//GEN-LAST:event_TritanopiaColoursActionPerformed

    private void CaptionImagesCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaptionImagesCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CaptionImagesCheckBoxActionPerformed

    private void MagnifyTextCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MagnifyTextCheckBoxActionPerformed
        if (MagnifyTextCheckBox.isSelected()) {
            MagnifiedTextSizeSettings();
        } else {
            NormalTextSizeSettings();
        }
        
    }//GEN-LAST:event_MagnifyTextCheckBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Menu().setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    public void defaultColoursSettings() {
        RedColourTest.setBackground(new Color(249, 6, 6));
        GreenColourTest.setBackground(new Color(0, 128, 0));
        BlueColourTest.setBackground(new Color(77, 77, 255));
        
        Seperator1.setBackground(new Color(249, 6, 6));
        Seperator2.setBackground(new Color(249, 6, 6));
    }
    
    public void DeuteranopiaColoursSettings() {
        RedColourTest.setBackground(new Color(238, 43, 150));
        GreenColourTest.setBackground(new Color(0, 155, 33));
        BlueColourTest.setBackground(new Color(0, 64, 224));
        
        Seperator1.setBackground(new Color(238, 43, 150));
        Seperator2.setBackground(new Color(238, 43, 150));
    }
    
    public void ProtanopiaColoursSettings() {
        RedColourTest.setBackground(new Color(250, 56, 143));
        GreenColourTest.setBackground(new Color(0, 128, 28));
        BlueColourTest.setBackground(new Color(6, 68, 224));
        
        Seperator1.setBackground(new Color(250, 56, 143));
        Seperator2.setBackground(new Color(250, 56, 143));
    }
    
    public void TritanopiaColoursSettings() {
        RedColourTest.setBackground(new Color(255, 0, 0));
        GreenColourTest.setBackground(new Color(0, 179, 60));
        BlueColourTest.setBackground(new Color(0, 0, 196));
        
        Seperator1.setBackground(new Color(255, 0, 0));
        Seperator2.setBackground(new Color(255, 0, 0));
    }
    
    public void MagnifiedTextSizeSettings() {
        AccessibilityOptionsLabel.setFont(new Font("Calibri", Font.PLAIN, 30));
        MagnifyTextCheckBox.setFont(new Font("Calibri", Font.PLAIN, 30));
        CaptionImagesCheckBox.setFont(new Font("Calibri", Font.PLAIN, 30));
        ColourblindModeLabel.setFont(new Font("Calibri", Font.PLAIN, 30));
        DefaultColours.setFont(new Font("Calibri", Font.PLAIN, 30));
        DeuteranopiaColours.setFont(new Font("Calibri", Font.PLAIN, 30));
        ProtanopiaColours.setFont(new Font("Calibri", Font.PLAIN, 30));
        TritanopiaColours.setFont(new Font("Calibri", Font.PLAIN, 30));
    }
    
    public void NormalTextSizeSettings() {
        AccessibilityOptionsLabel.setFont(new Font("Calibri", Font.PLAIN, 24));
        MagnifyTextCheckBox.setFont(new Font("Calibri", Font.PLAIN, 24));
        CaptionImagesCheckBox.setFont(new Font("Calibri", Font.PLAIN, 24));
        ColourblindModeLabel.setFont(new Font("Calibri", Font.PLAIN, 24));
        DefaultColours.setFont(new Font("Calibri", Font.PLAIN, 24));
        DeuteranopiaColours.setFont(new Font("Calibri", Font.PLAIN, 24));
        ProtanopiaColours.setFont(new Font("Calibri", Font.PLAIN, 24));
        TritanopiaColours.setFont(new Font("Calibri", Font.PLAIN, 24));    
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Settings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccessibilityOptionsLabel;
    private javax.swing.JPanel BlueColourTest;
    private javax.swing.JCheckBox CaptionImagesCheckBox;
    private javax.swing.ButtonGroup ColourblindButtonGroup;
    private javax.swing.JLabel ColourblindModeLabel;
    private javax.swing.JRadioButton DefaultColours;
    private javax.swing.JRadioButton DeuteranopiaColours;
    private javax.swing.JPanel GreenColourTest;
    private javax.swing.JCheckBox MagnifyTextCheckBox;
    private javax.swing.JRadioButton ProtanopiaColours;
    private javax.swing.JPanel RedColourTest;
    private javax.swing.JPanel Seperator1;
    private javax.swing.JPanel Seperator2;
    private javax.swing.JRadioButton TritanopiaColours;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
