/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUI.*;

/**
 *
 * @author usman
 */
public class BurnsQuiz extends javax.swing.JFrame {

    String userAnswer;

    /**
     * Creates new form Quiz
     */
    public BurnsQuiz() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(255, 255, 255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Question1Button = new javax.swing.JButton();
        Question2Button = new javax.swing.JButton();
        Question3Button = new javax.swing.JButton();
        Question4Button = new javax.swing.JButton();
        Question5Button = new javax.swing.JButton();
        SubmitButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Q1Panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Q1_1Answer = new javax.swing.JRadioButton();
        Q1_2Answer = new javax.swing.JRadioButton();
        Q1_3Answer = new javax.swing.JRadioButton();
        Q1_4Answer = new javax.swing.JRadioButton();
        Q2Panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Q2_1Answer = new javax.swing.JRadioButton();
        Q2_2Answer = new javax.swing.JRadioButton();
        Q2_3Answer = new javax.swing.JRadioButton();
        Q2_4Answer = new javax.swing.JRadioButton();
        Q3Panel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Q3_1Answer = new javax.swing.JRadioButton();
        Q3_2Answer = new javax.swing.JRadioButton();
        Q3_3Answer = new javax.swing.JRadioButton();
        Q3_4Answer = new javax.swing.JRadioButton();
        Q4Panel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Q4_1Answer = new javax.swing.JRadioButton();
        Q4_2Answer = new javax.swing.JRadioButton();
        Q4_3Answer = new javax.swing.JRadioButton();
        Q4_4Answer = new javax.swing.JRadioButton();
        Q5Panel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Q5_1Answer = new javax.swing.JRadioButton();
        Q5_2Answer = new javax.swing.JRadioButton();
        Q5_3Answer = new javax.swing.JRadioButton();
        Q5_4Answer = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(370, 680));
        setMinimumSize(new java.awt.Dimension(370, 680));
        setPreferredSize(new java.awt.Dimension(370, 680));
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Quiz/quizScreen.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 367, 185);

        jPanel2.setMaximumSize(new java.awt.Dimension(350, 246));
        jPanel2.setMinimumSize(new java.awt.Dimension(350, 246));

        Question1Button.setText("Question 1");
        Question1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Question1ButtonActionPerformed(evt);
            }
        });

        Question2Button.setText("Question 2");
        Question2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Question2ButtonActionPerformed(evt);
            }
        });

        Question3Button.setText("Question 3");
        Question3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Question3ButtonActionPerformed(evt);
            }
        });

        Question4Button.setText("Question 4");
        Question4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Question4ButtonActionPerformed(evt);
            }
        });

        Question5Button.setText("Question 5");
        Question5Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Question5ButtonActionPerformed(evt);
            }
        });

        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Question1Button, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addComponent(Question2Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Question3Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Question4Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Question5Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(SubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SubmitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Question1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Question2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(Question3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Question4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Question5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel3.setMaximumSize(new java.awt.Dimension(340, 235));
        jPanel3.setMinimumSize(new java.awt.Dimension(340, 235));
        jPanel3.setPreferredSize(new java.awt.Dimension(340, 235));

        Q1Panel.setMaximumSize(new java.awt.Dimension(340, 235));
        Q1Panel.setMinimumSize(new java.awt.Dimension(340, 235));

        jLabel2.setText("<html>Your sister has a burn and only puts it under cold water very briefly. How long should you run a burn under cold water for?</html>");

        buttonGroup1.add(Q1_1Answer);
        Q1_1Answer.setText("At least 10 seconds");

        buttonGroup1.add(Q1_2Answer);
        Q1_2Answer.setText("At least one minute");

        buttonGroup1.add(Q1_3Answer);
        Q1_3Answer.setText("At least ten minutes");

        buttonGroup1.add(Q1_4Answer);
        Q1_4Answer.setText("At least 1 hour");

        javax.swing.GroupLayout Q1PanelLayout = new javax.swing.GroupLayout(Q1Panel);
        Q1Panel.setLayout(Q1PanelLayout);
        Q1PanelLayout.setHorizontalGroup(
            Q1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Q1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Q1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Q1_4Answer)
                    .addComponent(Q1_3Answer)
                    .addComponent(Q1_2Answer)
                    .addComponent(Q1_1Answer))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        Q1PanelLayout.setVerticalGroup(
            Q1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Q1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Q1_1Answer)
                .addGap(18, 18, 18)
                .addComponent(Q1_2Answer)
                .addGap(18, 18, 18)
                .addComponent(Q1_3Answer)
                .addGap(18, 18, 18)
                .addComponent(Q1_4Answer)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        Q2Panel.setMaximumSize(new java.awt.Dimension(340, 235));
        Q2Panel.setMinimumSize(new java.awt.Dimension(340, 235));

        jLabel3.setText("<html>You’re camping with a friend, when they get a burn from their hot chocolate. There is no tap nearby. Which of the following could you use immediately to cool the burn?</html>");

        buttonGroup2.add(Q2_1Answer);
        Q2_1Answer.setText("Dirty washing up water");

        buttonGroup2.add(Q2_2Answer);
        Q2_2Answer.setText("Tepid old coffee");

        buttonGroup2.add(Q2_3Answer);
        Q2_3Answer.setText("Fizzy drinks from your cool box");

        buttonGroup2.add(Q2_4Answer);
        Q2_4Answer.setText("None of these");

        javax.swing.GroupLayout Q2PanelLayout = new javax.swing.GroupLayout(Q2Panel);
        Q2Panel.setLayout(Q2PanelLayout);
        Q2PanelLayout.setHorizontalGroup(
            Q2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Q2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Q2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(Q2PanelLayout.createSequentialGroup()
                        .addGroup(Q2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Q2_4Answer)
                            .addComponent(Q2_3Answer)
                            .addComponent(Q2_2Answer)
                            .addComponent(Q2_1Answer))
                        .addGap(0, 147, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Q2PanelLayout.setVerticalGroup(
            Q2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Q2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Q2_1Answer)
                .addGap(18, 18, 18)
                .addComponent(Q2_2Answer)
                .addGap(18, 18, 18)
                .addComponent(Q2_3Answer)
                .addGap(18, 18, 18)
                .addComponent(Q2_4Answer)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        Q3Panel.setMaximumSize(new java.awt.Dimension(340, 235));
        Q3Panel.setMinimumSize(new java.awt.Dimension(340, 235));

        jLabel4.setText("<html>If someone has a burn, what is the key action you can take to help?</html>");

        buttonGroup3.add(Q3_1Answer);
        Q3_1Answer.setText("Clean the burn");

        buttonGroup3.add(Q3_2Answer);
        Q3_2Answer.setText("Cover the burn");

        buttonGroup3.add(Q3_3Answer);
        Q3_3Answer.setText("Cool the burn");

        buttonGroup3.add(Q3_4Answer);
        Q3_4Answer.setText("None of these");

        javax.swing.GroupLayout Q3PanelLayout = new javax.swing.GroupLayout(Q3Panel);
        Q3Panel.setLayout(Q3PanelLayout);
        Q3PanelLayout.setHorizontalGroup(
            Q3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Q3PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Q3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addGroup(Q3PanelLayout.createSequentialGroup()
                        .addGroup(Q3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Q3_4Answer)
                            .addComponent(Q3_3Answer)
                            .addComponent(Q3_2Answer)
                            .addComponent(Q3_1Answer))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Q3PanelLayout.setVerticalGroup(
            Q3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Q3PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Q3_1Answer)
                .addGap(18, 18, 18)
                .addComponent(Q3_2Answer)
                .addGap(18, 18, 18)
                .addComponent(Q3_3Answer)
                .addGap(18, 18, 18)
                .addComponent(Q3_4Answer)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        Q4Panel.setMaximumSize(new java.awt.Dimension(340, 235));
        Q4Panel.setMinimumSize(new java.awt.Dimension(340, 235));

        jLabel5.setText("<html>After you have cooled a burn, what everyday item can you use to cover it?</html>");

        buttonGroup4.add(Q4_1Answer);
        Q4_1Answer.setText("Cling film");

        buttonGroup4.add(Q4_2Answer);
        Q4_2Answer.setText("Cotton wool");

        buttonGroup4.add(Q4_3Answer);
        Q4_3Answer.setText("Kitchen foil");

        buttonGroup4.add(Q4_4Answer);
        Q4_4Answer.setText("Kitchen roll");

        javax.swing.GroupLayout Q4PanelLayout = new javax.swing.GroupLayout(Q4Panel);
        Q4Panel.setLayout(Q4PanelLayout);
        Q4PanelLayout.setHorizontalGroup(
            Q4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Q4PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Q4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addGroup(Q4PanelLayout.createSequentialGroup()
                        .addGroup(Q4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Q4_4Answer)
                            .addComponent(Q4_3Answer)
                            .addComponent(Q4_2Answer)
                            .addComponent(Q4_1Answer))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Q4PanelLayout.setVerticalGroup(
            Q4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Q4PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Q4_1Answer)
                .addGap(18, 18, 18)
                .addComponent(Q4_2Answer)
                .addGap(18, 18, 18)
                .addComponent(Q4_3Answer)
                .addGap(18, 18, 18)
                .addComponent(Q4_4Answer)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        Q5Panel.setMaximumSize(new java.awt.Dimension(340, 235));
        Q5Panel.setMinimumSize(new java.awt.Dimension(340, 235));

        jLabel6.setText("<html>You are helping your grandma make some soup, when she tips the boiling stock over her arm. You know you have to quickly cool the burn. How does this action help her?</html>");

        buttonGroup5.add(Q5_1Answer);
        Q5_1Answer.setText("Reduces the pain and risk of scarring");

        buttonGroup5.add(Q5_2Answer);
        Q5_2Answer.setText("Prevents infection");

        buttonGroup5.add(Q5_3Answer);
        Q5_3Answer.setText("Prevents further injuries");

        buttonGroup5.add(Q5_4Answer);
        Q5_4Answer.setText("Increases the pain");

        javax.swing.GroupLayout Q5PanelLayout = new javax.swing.GroupLayout(Q5Panel);
        Q5Panel.setLayout(Q5PanelLayout);
        Q5PanelLayout.setHorizontalGroup(
            Q5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Q5PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Q5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(Q5PanelLayout.createSequentialGroup()
                        .addGroup(Q5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Q5_4Answer)
                            .addComponent(Q5_2Answer)
                            .addComponent(Q5_1Answer)
                            .addComponent(Q5_3Answer))
                        .addGap(0, 117, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Q5PanelLayout.setVerticalGroup(
            Q5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Q5PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Q5_1Answer)
                .addGap(18, 18, 18)
                .addComponent(Q5_2Answer)
                .addGap(18, 18, 18)
                .addComponent(Q5_3Answer)
                .addGap(18, 18, 18)
                .addComponent(Q5_4Answer)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Q1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Q2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Q3Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Q4Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Q5Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 235, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Q1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Q2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Q3Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Q4Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Q5Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 190, 370, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        // TODO add your handling code here:
        try {
            this.calPoint();
            Scores obj = new Scores();
            obj.setVisible(true);
            obj.getPoints(this.Points);
            this.dispose();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void Question1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Question1ButtonActionPerformed
        // TODO add your handling code here:
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();
        
        jPanel3.add(Q1Panel);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_Question1ButtonActionPerformed

    private void Question2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Question2ButtonActionPerformed
        // TODO add your handling code here:
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();
        
        jPanel3.add(Q2Panel);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_Question2ButtonActionPerformed

    private void Question3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Question3ButtonActionPerformed
        // TODO add your handling code here:
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();
        
        jPanel3.add(Q3Panel);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_Question3ButtonActionPerformed

    private void Question4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Question4ButtonActionPerformed
        // TODO add your handling code here:
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();
        
        jPanel3.add(Q4Panel);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_Question4ButtonActionPerformed

    private void Question5ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Question5ButtonActionPerformed
        // TODO add your handling code here:
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();
        
        jPanel3.add(Q5Panel);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_Question5ButtonActionPerformed

    public  double marks=0.0;
      
       public double Points=0.0;
       public void calPoint(){
           marks=0.0;
           if(Q1_3Answer.isSelected()==true){
               marks+=60.0;
           }
           if(Q2_3Answer.isSelected()==true){
               marks+=60.0;
           }
           if(Q3_3Answer.isSelected()==true){
              marks+=60.0;
           } 
           if(Q4_1Answer.isSelected()==true){
              marks+=60.0;
           }
           if(Q5_1Answer.isSelected()==true){
              marks+=60.0;
           }
           Points=marks;
       }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BurnsQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BurnsQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BurnsQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BurnsQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BurnsQuiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Q1Panel;
    private javax.swing.JRadioButton Q1_1Answer;
    private javax.swing.JRadioButton Q1_2Answer;
    private javax.swing.JRadioButton Q1_3Answer;
    private javax.swing.JRadioButton Q1_4Answer;
    private javax.swing.JPanel Q2Panel;
    private javax.swing.JRadioButton Q2_1Answer;
    private javax.swing.JRadioButton Q2_2Answer;
    private javax.swing.JRadioButton Q2_3Answer;
    private javax.swing.JRadioButton Q2_4Answer;
    private javax.swing.JPanel Q3Panel;
    private javax.swing.JRadioButton Q3_1Answer;
    private javax.swing.JRadioButton Q3_2Answer;
    private javax.swing.JRadioButton Q3_3Answer;
    private javax.swing.JRadioButton Q3_4Answer;
    private javax.swing.JPanel Q4Panel;
    private javax.swing.JRadioButton Q4_1Answer;
    private javax.swing.JRadioButton Q4_2Answer;
    private javax.swing.JRadioButton Q4_3Answer;
    private javax.swing.JRadioButton Q4_4Answer;
    private javax.swing.JPanel Q5Panel;
    private javax.swing.JRadioButton Q5_1Answer;
    private javax.swing.JRadioButton Q5_2Answer;
    private javax.swing.JRadioButton Q5_3Answer;
    private javax.swing.JRadioButton Q5_4Answer;
    private javax.swing.JButton Question1Button;
    private javax.swing.JButton Question2Button;
    private javax.swing.JButton Question3Button;
    private javax.swing.JButton Question4Button;
    private javax.swing.JButton Question5Button;
    private javax.swing.JButton SubmitButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
