/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author up873711
 */
public class Lesson extends javax.swing.JFrame {

    /**
     * Creates new form Lesson
     */
    public Lesson() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(255,255,255));
        setLocationRelativeTo(null);
    }

    
    public void CPR() {
        TextLabel.setText("<html>Place some relevant text here</html>");
        TextLabel.setText("");
        ImageLabel.setIcon(new ImageIcon(getClass().getResource("/Lesson/how-to-do-CPR.png")));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StatusBar = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        TextLabel = new javax.swing.JLabel();
        ImageLabel = new javax.swing.JLabel();
        HeaderBackground = new javax.swing.JLabel();
        HeaderBackground1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        StatusBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lesson/lessonScreen.png"))); // NOI18N
        getContentPane().add(StatusBar);
        StatusBar.setBounds(-20, 0, 380, 170);

        BackButton.setBackground(new java.awt.Color(255, 51, 51));
        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/back.png"))); // NOI18N
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton);
        BackButton.setBounds(20, 40, 30, 60);

        TextLabel.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        TextLabel.setText("<html>insert method desciptions here</html>");
        getContentPane().add(TextLabel);
        TextLabel.setBounds(20, 340, 300, 90);

        ImageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImageLabel.setText("<insert image here>");
        getContentPane().add(ImageLabel);
        ImageLabel.setBounds(10, 180, 330, 140);

        HeaderBackground.setBackground(new java.awt.Color(249, 6, 6));
        HeaderBackground.setPreferredSize(new java.awt.Dimension(360, 110));
        getContentPane().add(HeaderBackground);
        HeaderBackground.setBounds(0, 0, 360, 110);

        HeaderBackground1.setBackground(new java.awt.Color(249, 6, 6));
        HeaderBackground1.setPreferredSize(new java.awt.Dimension(360, 110));
        getContentPane().add(HeaderBackground1);
        HeaderBackground1.setBounds(0, 0, 360, 110);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        new Menu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        CPR();
    }//GEN-LAST:event_formWindowActivated

    
    public void defaultColoursSettings(){
        HeaderBackground.setBackground(new Color(249, 6, 6));
    }
    
    public void DeuteranopiaColoursSettings(){
        HeaderBackground.setBackground(new Color(238, 43, 150));
    }
    
    public void ProtanopiaColoursSettings(){
        HeaderBackground.setBackground(new Color(250, 56, 143));
    }
    
    public void TritanopiaColoursSettings(){
        HeaderBackground.setBackground(new Color(255, 0, 0));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lesson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lesson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lesson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lesson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lesson().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel HeaderBackground;
    private javax.swing.JLabel HeaderBackground1;
    private javax.swing.JLabel ImageLabel;
    private javax.swing.JLabel StatusBar;
    private javax.swing.JLabel TextLabel;
    // End of variables declaration//GEN-END:variables
}
