package GUI;


import java.awt.Color;
import java.awt.Container;

public class Menu extends javax.swing.JFrame {

    public Container viewMenu;

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(255, 255, 255));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LessonButton = new javax.swing.JButton();
        QuizButton = new javax.swing.JButton();
        PreviewResultsButton = new javax.swing.JButton();
        ScoresButton = new javax.swing.JButton();
        EmergencyButton = new javax.swing.JButton();
        SettingsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(360, 640));
        setResizable(false);
        setSize(new java.awt.Dimension(360, 640));

        LessonButton.setBackground(new java.awt.Color(249, 6, 6));
        LessonButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageFiles/iconLessons_transparent.png"))); // NOI18N
        LessonButton.setMaximumSize(new java.awt.Dimension(159, 169));
        LessonButton.setMinimumSize(new java.awt.Dimension(159, 169));
        LessonButton.setPreferredSize(new java.awt.Dimension(108, 129));
        LessonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LessonButtonActionPerformed(evt);
            }
        });

        QuizButton.setBackground(new java.awt.Color(249, 6, 6));
        QuizButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageFiles/iconQuiz_transparent.png"))); // NOI18N
        QuizButton.setPreferredSize(new java.awt.Dimension(108, 129));
        QuizButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuizButtonActionPerformed(evt);
            }
        });

        PreviewResultsButton.setBackground(new java.awt.Color(249, 6, 6));
        PreviewResultsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageFiles/iconResults_transparent.png"))); // NOI18N
        PreviewResultsButton.setPreferredSize(new java.awt.Dimension(108, 129));
        PreviewResultsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreviewResultsButtonActionPerformed(evt);
            }
        });

        ScoresButton.setBackground(new java.awt.Color(249, 6, 6));
        ScoresButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageFiles/iconScores_transparent.png"))); // NOI18N
        ScoresButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScoresButtonActionPerformed(evt);
            }
        });

        EmergencyButton.setBackground(new java.awt.Color(249, 6, 6));
        EmergencyButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageFiles/iconEmergency_transparent.png"))); // NOI18N
        EmergencyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmergencyButtonActionPerformed(evt);
            }
        });

        SettingsButton.setBackground(new java.awt.Color(249, 6, 6));
        SettingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PreviewResultsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LessonButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmergencyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(QuizButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ScoresButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SettingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LessonButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QuizButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PreviewResultsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ScoresButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmergencyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SettingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LessonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LessonButtonActionPerformed
        new LessonList().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_LessonButtonActionPerformed

    private void QuizButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuizButtonActionPerformed
        new QuizList().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_QuizButtonActionPerformed

    private void ScoresButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScoresButtonActionPerformed
        new Scores().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ScoresButtonActionPerformed

    private void EmergencyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmergencyButtonActionPerformed
        //new Emergency().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_EmergencyButtonActionPerformed

    private void PreviewResultsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreviewResultsButtonActionPerformed
        new PreviewResultsList().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_PreviewResultsButtonActionPerformed

    private void SettingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingsButtonActionPerformed
        new Settings().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_SettingsButtonActionPerformed
    
    public void defaultColoursMenu(){
        LessonButton.setBackground(new Color(249, 6, 6));
        QuizButton.setBackground(new Color(249, 6, 6));
        PreviewResultsButton.setBackground(new Color(249, 6, 6));
        ScoresButton.setBackground(new Color(249, 6, 6));
        EmergencyButton.setBackground(new Color(249, 6, 6));
        SettingsButton.setBackground(new Color(249, 6, 6));
    }
    
    public void DeuteranopiaColoursMenu(){
        LessonButton.setBackground(new Color(238, 43, 150));
        QuizButton.setBackground(new Color(238, 43, 150));
        PreviewResultsButton.setBackground(new Color(238, 43, 150));
        ScoresButton.setBackground(new Color(238, 43, 150));
        EmergencyButton.setBackground(new Color(238, 43, 150));
        SettingsButton.setBackground(new Color(238, 43, 150));

    }
    
    public void ProtanopiaColoursMenu(){
        LessonButton.setBackground(new Color(250, 56, 143));
        QuizButton.setBackground(new Color(250, 56, 143));
        PreviewResultsButton.setBackground(new Color(250, 56, 143));
        ScoresButton.setBackground(new Color(250, 56, 143));
        EmergencyButton.setBackground(new Color(250, 56, 143));
        SettingsButton.setBackground(new Color(250, 56, 143));
    }
    
    public void TritanopiaColoursMenu(){
        LessonButton.setBackground(new Color(255, 0, 0));
        QuizButton.setBackground(new Color(255, 0, 0));
        PreviewResultsButton.setBackground(new Color(255, 0, 0));
        ScoresButton.setBackground(new Color(255, 0, 0));
        EmergencyButton.setBackground(new Color(255, 0, 0));
        SettingsButton.setBackground(new Color(255, 0, 0));
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EmergencyButton;
    private javax.swing.JButton LessonButton;
    private javax.swing.JButton PreviewResultsButton;
    private javax.swing.JButton QuizButton;
    private javax.swing.JButton ScoresButton;
    private javax.swing.JButton SettingsButton;
    // End of variables declaration//GEN-END:variables

}
